### ISSUE TITLE
add branch filter to list_commits()

### ISSUE THREAD

**Issue by RaananHadar** [itssimon/pachypy#3]
**Is your feature request related to a problem? Please describe.**
When listing commits in a repo, you cannot easilly filter between branches such as 'master', 'stats' etc.

**Describe the solution you'd like**
Add an optional branch argument to list_commits() that will filter the results by branch similar to list_files().

**Describe alternatives you've considered**
I attempted to filter the resulting dataframe manually however there is currently a bug, see https://github.com/itssimon/pachypy/issues/2

**Comment by RaananHadar** [comment]
hope you enjoyed your vacation :)
My main issue is that I am trying to differentiate between the commits to the actual repo and stats branch in order to look only at metrics or logs for example.

So basically the main issue is that the stats branch is a special one and doesn't really hold the same data as the repo and list_commits() returns a mangled response.

**Comment by itssimon** [comment]
I see. Pachyderm does not support this but pachypy could traverse the commit provenance and backfill the branch field. I'm happy to implement this for list_commits().

**Comment by RaananHadar** [comment]
thank you, this would make your client much more useful. I am wondering if we should open an issue on the pachyderm client for this?
